name: ë²„ê·¸ ë¦¬í¬íŠ¸ ðŸž
description: >-
  ë°œê²¬í•œ ë²„ê·¸ì— ëŒ€í•œ ì •ë³´ë¥¼ ìž…ë ¥í•´ì£¼ì„¸ìš”.
title: '[bug]: '
labels:
  - ìˆ˜ì •
  - ë²„ê·¸
body:
  - type: textarea
    id: description
    attributes:
      label: ë²„ê·¸ ì„¤ëª…
      description: ë²„ê·¸ì— ëŒ€í•´ ëª…í™•í•˜ê²Œ ì„¤ëª…í•˜ì—¬ ì£¼ì„¸ìš”
    validations:
      required: true
  - type: input
    id: repro-link
    attributes:
      label: ë§í¬
      description: >-
        ë¬¸ì œê°€ ë°œìƒí•œ ì§€ì ì— ëŒ€í•˜ì—¬ ë§í¬ë¥¼ ì‚½ìž…í•´ì£¼ì„¸ìš”.
        
        ì¤‘ìš”: ë§Œì•½ ì œê³µëœ URLì´ ìž˜ëª»ë˜ì—ˆì„ ê²½ìš° (ì˜ˆ: 404 ì˜¤ë¥˜ ë˜ëŠ” ë¹„ê³µê°œ ì €ìž¥ì†Œ), ìš°ë¦¬ëŠ” ì´ìŠˆë¥¼ ë‹«ì„ ìˆ˜ ìžˆìŠµë‹ˆë‹¤.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: ë¬¸ì œ ë¬˜ì‚¬
      description: >-
        ì‚½ìž…í•œ ë§í¬ë¥¼ ì´ìš©í•´ì„œ ì´ìŠˆì— ëŒ€í•´ ë¬˜ì‚¬í•˜ì—¬ì£¼ì„¸ìš”. ë˜í•œ ë‹¹ì‹ ì´ ë°œìƒí•  ê²ƒì´ë¼ ì˜ˆìƒë˜ëŠ” ë¶€ë¶„ì— ëŒ€í•´ì„œë„ ì„œìˆ í•´ì£¼ì„¸ìš”.
      placeholder: >-
        1. Go to above link
        
        2. Click on '....'
        
        3. ...
  - type: textarea
    id: system
    attributes:
      label: System
      description: Please paste the results of `npx storybook@latest info` here.
      render: bash
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.